Feature/document ui
ESD6-blockr/blockr-wallet pull request #11
Opened 2019-06-13 16:23 UTC by BasJoosten

2019-06-14 12:08 UTC, timofudala requested changes

2019-06-14 12:08 UTC, TimoF97 commented on src/components/overview/feedback/feedback_mock/feedback.json
> +                "value": "Dit is niet te lezen man....",
Please change all the text to english. Please also use professional texts. There are quite unprofessional.

2019-06-16 08:24 UTC, roelvdboom commented
This pull request should be created to the develop branch. Not to the ui-ux branch.

2019-06-16 10:15 UTC, BasJoosten commented
> This pull request should be created to the develop branch. Not to the ui-ux branch.

Closing this pull request and creating one for the development branch

2019-06-16 10:15 UTC, closed without merging