Feature/smart contract integration
ESD6-blockr/blockr-wallet pull request #12
Opened 2019-06-14 11:33 UTC by Rikvanmaaren

Most data used is mocked in this branch since no test data could be retrieved.

2019-06-14 12:00 UTC, ronaldvandenbroek approved these changes

2019-06-14 12:00 UTC, ronaldvandenbroek commented on src/contract/contract.parser.ts
> +            // functionJson.push(this.parseFunctionContract(functionName, params));
Klopt het dat deze functie uitgecomment staat?

2019-06-14 12:00 UTC, ronaldvandenbroek commented on tsconfig.json
> +    "checkJs": false,
Klopt het dat jullie de volledige tsconfig ombouwen hier?

2019-06-17 09:26 UTC, roelvdboom commented
Because of a recently merged pull request, this branch has some merge conflicts. Please resolve those.

2019-06-17 19:05 UTC, Juuldamen requested changes
Currently this PR wants to add old versions of files that are already in the develop branch. This PR would revert all those changes done. Merge the latest version of develop into the smart-contract-integration branch to resolve this.

Example profile.tsx in PR
![chrome_7CZQOVSvcM](https://user-images.githubusercontent.com/31408341/59629481-3afce780-9143-11e9-8c58-109c9befa488.png)

Example profile.tsx in develop
![chrome_eLdSdlSEJO](https://user-images.githubusercontent.com/31408341/59629612-86af9100-9143-11e9-993b-97d9b72e1319.png)

2025-12-10 15:24 UTC, closed without merging