Feature BLO-68 and BLO-70  UI UX + Redux implementation
ESD6-blockr/blockr-wallet pull request #2
Opened 2019-05-28 11:46 UTC by roelvdboom

Also contains some work from BLO-70.

Login
![image](https://user-images.githubusercontent.com/25582889/58475616-bffd6e00-814e-11e9-8f9e-038c217348bf.png)

Profile
![image](https://user-images.githubusercontent.com/25582889/58475639-d3a8d480-814e-11e9-8cfe-c82f7e40c458.png)

Create Transaction (Missing create button)
![image](https://user-images.githubusercontent.com/25582889/58475653-dacfe280-814e-11e9-8c93-243ca6efcb0d.png)

Transaction detail
![image](https://user-images.githubusercontent.com/25582889/58475674-eb805880-814e-11e9-9eab-0ca61bed9ca9.png)

2019-05-28 13:43 UTC, timofudala requested changes

2019-05-28 13:43 UTC, TimoF97 commented on src/__tests__/components/login.test.tsx
> +        // TODO: Test if state is set correctly
Please implement this TODO.

2019-05-28 13:43 UTC, TimoF97 commented on src/components/login/login.tsx
> +    public login = () => {
Please conform to the React naming of `handle` in front of the actual name, so: `handleLogin`.
Please apply this throughout the entire application.

2019-05-28 13:43 UTC, TimoF97 commented on src/services/apiService.ts
> +const publicApiUrl = "https://public.blockr.verux.nl";
Please make these constants outside the scope of a class with upper case, so `PUBLIC_API_URL`.

2019-05-28 13:43 UTC, TimoF97 commented on src/services/apiService.ts
> +        logger.info("Within api Service");
Please remove this logging.

2019-05-28 15:02 UTC, timofudala submitted a review, later dismissed

2019-05-28 15:02 UTC, TimoF97 commented on src/components/profile/profile.tsx
> +    public handleTransactionView = (transaction: Transaction) => {
I appreciate you conforming to the `handle` aspect now. However, please change this function name to `handleTransactionViewNavigation`.

2019-05-29 07:41 UTC, TimoF97 commented on src/components/createTransaction/createTransaction.tsx
> +import { Transaction, TransactionType } from "@blockr/blockr-models";
Your file naming is inconsistent within this folder and potentially in other folders as well.

2019-05-29 08:01 UTC, saltz submitted a review, later dismissed
Remove the jest section from the `package.json` file. And if published add a `.npmignore` file.

2019-06-11 13:00 UTC, Juuldamen commented on Jenkinsfile
> +    sonar_exclusions: "src/*"
Why are all source files excluded?

2019-06-11 13:06 UTC, RikvanSpreuwel approved these changes

2019-06-11 13:08 UTC, hugovandevliert submitted a review, later dismissed

2019-06-11 13:08 UTC, HugovandeVliert commented on src/components/application.tsx
> +// let validatorIp: string | undefined;
Please remove this commented out code

2019-06-11 13:08 UTC, HugovandeVliert commented on src/main.ts
>      // TODO: Add catch
Please finish this TODO

2019-06-11 13:20 UTC, Juuldamen requested changes

2019-06-11 13:20 UTC, Juuldamen commented on src/main.ts
>      // TODO: Add catch
Resolve this TODO.

2019-06-11 13:20 UTC, Juuldamen commented on src/reducers/index.ts
> +import { combineReducers, Reducer } from "redux";
Remove this unused import.

```suggestion
import { combineReducers } from "redux";
```

2019-06-11 13:26 UTC, Juuldamen approved these changes

2019-06-11 13:36 UTC, merged